export const typeRedux = {
  setUserLogin: 'SET_USER_LOGIN',
  setUserLogout: 'SET_USER_LOGOUT',
  setUserAvatar: 'SET_USER_AVATAR',
  setUserName: 'SET_USER_NAME',
  setAllProduct: 'SET_PRODUCTS_COLLECTION',
  setProductItem: 'SET_PRODUCT_ITEM',
  setAddToCartProducts: 'SET_ADD_TO_CART_PRODUCTS',
  setPricingCart: 'SET_PRICING_CART',
  // setSingleCart: 'SET_SINGLE_CART',
  setSearching: 'SET_SEARCHING',
  setChooseProductId: 'SET_CHOOSE_PRODUCT_ID',
  setChooseProductCount: 'SET_CHOOSE_PRODUCT_Price',
  setChooseProductColor: 'SET_CHOOSE_PRODUCT_Color',
  setChooseProductSize: 'SET_CHOOSE_PRODUCT_Size',
  setChooseProductTotal: 'SET_CHOOSE_PRODUCT_Total',
};
